-- Add 30 more crypto twitter memes about poor takes and disagreement
-- These memes are responses to bad takes, disagreement, and questionable opinions

INSERT INTO meme_responses (url, caption, is_active) VALUES
  ('https://i.giphy.com/media/l3q2K5jinAlChoCLS/giphy.gif', 'Chief called, this ain''t it'),
  ('https://i.giphy.com/media/KGSxFwJJHQPsKzzFba/giphy.gif', 'Tell me you''re ngmi without telling me'),
  ('https://i.giphy.com/media/l0HlvtIPzPdt2usKs/giphy.gif', 'This take aged like milk'),
  ('https://i.giphy.com/media/G4ZNYMQVMH6us/giphy.gif', 'Respectfully, no'),
  ('https://i.giphy.com/media/8vUEXZA2me7vnuUvrs/giphy.gif', 'Ser, this is a Wendy''s'),
  ('https://i.giphy.com/media/STfLOU6iRBRunMciZv/giphy.gif', 'That''s gonna be a yikes from me'),
  ('https://i.giphy.com/media/3o85xIO33l7RlmLR4I/giphy.gif', 'The delusion is strong with this one'),
  ('https://i.giphy.com/media/jeXiz1RAvzX44/giphy.gif', 'My brother in Christ, no'),
  ('https://i.giphy.com/media/l3vRfwkKcokQQAstr/giphy.gif', 'Not financial advice but maybe reconsider'),
  ('https://i.giphy.com/media/5t9wJjyHAOxvnxcPNk/giphy.gif', 'Sir this is not the way'),
  ('https://i.giphy.com/media/3o7btZ1Gm7ZL25pLMs/giphy.gif', 'You just bought the top didn''t you'),
  ('https://i.giphy.com/media/l1J9u3TZfpmeDLkD6/giphy.gif', 'This tweet will not age well'),
  ('https://i.giphy.com/media/l0MYC0LajbaPoEADu/giphy.gif', 'Have fun staying poor I guess'),
  ('https://i.giphy.com/media/xUA7bdpLxQhsSQdyog/giphy.gif', 'Imagine thinking this unironically'),
  ('https://i.giphy.com/media/3o6Zt4HU9uwXmXSAuI/giphy.gif', 'Couldn''t be more wrong if you tried'),
  ('https://i.giphy.com/media/l3vR85PnGsBwu1PFK/giphy.gif', 'Delete this nephew'),
  ('https://i.giphy.com/media/l4Ki2obCyAQS5WhFe/giphy.gif', 'The cope is unreal'),
  ('https://i.giphy.com/media/l3q2umc327t2nzSOQ/giphy.gif', 'This is why we can''t have nice things'),
  ('https://i.giphy.com/media/1zSz5MVw4zKg0/giphy.gif', 'Username checks out'),
  ('https://i.giphy.com/media/l3vRgiN4fSg8rkJy0/giphy.gif', 'You must be fun at parties'),
  ('https://i.giphy.com/media/3oz8xLd9DJq2l2VFtu/giphy.gif', 'Proof of work: failed'),
  ('https://i.giphy.com/media/l4FGuhL4U2WyjdkaY/giphy.gif', 'This ain''t it fam'),
  ('https://i.giphy.com/media/26n6Gx9moCgs1pUuk/giphy.gif', 'We need to talk about your takes'),
  ('https://i.giphy.com/media/l0MYt5jPR6QX5pnqM/giphy.gif', 'Pack it up, that''s enough internet for today'),
  ('https://i.giphy.com/media/dEdmW17JnZhiU/giphy.gif', 'Every word you just said was wrong'),
  ('https://i.giphy.com/media/l3q2XhfQ8oCkm1Ts4/giphy.gif', 'Time to log off and touch grass'),
  ('https://i.giphy.com/media/26n6WywJyh39n1pBu/giphy.gif', 'That''s a bold strategy Cotton'),
  ('https://i.giphy.com/media/3oxRmGXbquXKz6DNPq/giphy.gif', 'The market is going to humble you'),
  ('https://i.giphy.com/media/l3q2K5jinAlChoCLS/giphy.gif', 'Bags getting heavy huh'),
  ('https://i.giphy.com/media/AAsj7jdrHjtp6/giphy.gif', 'This take is not gonna make it');
